# 替换字符配置
replace_chars:
  cn: "*" # 中文违规词替换为星号
  en: "#" # 英文违规词替换为井号

# 禁止使用的词汇
banned_words:
  # 中文违规词
  cn:
    - "脏话"
    - "敏感词"
    - "违规词"
    - "不良内容"
    - "操"
    - "傻逼"
    - "鸡巴"
    - "出生"
    - "去你的"
    - "操你妈"
    - "迷你"
    - "死"
    - "大日本帝国"
    - "艹"
    - "黄"
    - "瞎了吧"
    - "看片"
    - "撸"
    - "导管"
    - "屁股"
    - "傻子"
    - "大傻子"
    - "猪逼吧？怎么这么菜"
    - "乐子"
    - "牛逼"
    - "逼"
    - "去你丫的"
    - "他妈的"
    - "端口"
    - "你个狗"
    - "91xm.com"
  
  # 英文违规词
  en:
    - "fuck"
    - "shit"
    - "asshole"
    - "bitch"
    - "idiot"
    - "fuck you"
    - "djb"
    - "jb"
    - "sb"
    - "nb"
    - "cnm"
    - "tmd"
    - "cnnd"
    - "mini"
    - "si"
    - "ass"
    - "91n"
    - "www..com"
    - "www.91n.con"
    - "Fuck you"
    - "sd"
    - "fuckyou"
    - "funk you"
    - "fuke you"
    - "www."
    - ".com"
    - "fm.rainplay.cn"
    - ".cn"
    - "https://"
    - "http://"
    - "https;//"
    - "http;//"
    - "917813"
    - "91"
    - "78"
    - "13"
    - "nb"
    - "ip"
    - "admin"
    - "owner"
    - "moderator"
    - "server"
    - "op"
    - "hacker"
    - "cheater"
    - "917813"
    - "sb"
    - "djb"
    - "250"
    - "cnm"
    - "tmd"
    - "cnnd"
    - "ass"
    - "Fuck you"
    - "sd"
    - "91xm.com"

# 插件设置
settings:
  notify_player: true    # 是否通知玩家内容被过滤
  log_filtered: true     # 是否记录过滤日志